language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
before_install:
  - echo "extension=ldap.so" >>php --ini | grep "Loaded Configuration" | sed -e "s|.:\s||"``
env:
  - CI_JOB=lint_syntax
  - CI_JOB=lint_style
matrix:
  exclude:
    - php: '7.1'
      env: CI_JOB=lint_style
    - php: '7.2'
      env: CI_JOB=lint_style
script:
  - bash ci/ci.sh --dir ./
